version: "3.8"

services:
  mariadb:
    image: mariadb:11.4
    container_name: meeting-one-line-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: meeting_one_line
      MYSQL_USER: meeting_user
      MYSQL_PASSWORD: meeting_pass
    ports:
      - "3306:3306" # host(로컬) 3306 → container 3306
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb_data:
